apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: symfony
      tier: backend
  template:
    metadata:
      labels:
        app: symfony
        tier: backend
    spec:
      containers:
        - name: php-fpm
          image: {{ .Values.php.image.image }}
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"