apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.nginx.service.port }}
      targetPort: 80
      {{- if eq .Values.nginx.service.type "NodePort" }}
      nodePort: {{ .Values.nginx.service.nodePort }}
      {{- end }}
  selector:
    app: symfony
    tier: frontend